### ISSUE TITLE
Tabs are misplaced when the window is not maximized

### ISSUE THREAD

**Issue by itoshkov** [harveycabaguio/firefox-elementary-theme#11] opened 2018-06-20 16:00 UTC
Tabs look OK when the window is maximized:
![firefox - maximized](https://user-images.githubusercontent.com/360805/41670131-1a7abc16-74bc-11e8-9544-88c119359b1d.png)

But they are moved down a bit when it's not:
![firefox - unmaximized](https://user-images.githubusercontent.com/360805/41670129-1a3de4c6-74bc-11e8-93ca-ed001679f025.png)

**Comment by harveycabaguio** [comment] 2018-06-21 02:14
I can't reproduce, my tabs look fine in both maximized and unmaximized windows. What addons do you have installed? Wondering if one of them might be causing it.

**Comment by itoshkov** [comment] 2018-06-21 13:11
I have:
- Firefox Multi-Account Containers
- snoozetabs
- Test Pilot

**Comment by itoshkov** [comment] 2018-06-21 13:17
I removed all my extensions and restarted Firefox but it didn't help. I also had 2 pinned tabs, which I unpinned and restarted but still no change with regards the tabs placement.

The tabs look OK though, while the menu is shown (press Alt once). When the menu hides, we're back to the same bad state.

**Comment by hiunnhue** [comment] 2018-06-23 22:13
I can reproduce this too.
It seems like we have to check the option "Drag Space" to trigger it.
　

![image](https://user-images.githubusercontent.com/1015601/41814052-4e2847c0-7775-11e8-877d-20b924598bf8.png)

**Comment by itoshkov** [comment] 2018-06-24 13:05
Yes, "Drag Space" is the culprit!

**Comment by harveycabaguio** [comment] 2018-06-24 14:34
Should be fixed now

**Closed as completed by harveycabaguio** 2018-06-24 14:34 UTC
Labels: needs info
